language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "j/Z4JIBQbpTl69+rDJmtfpgkVNdsp9BNhWqXumDgqHdBAetF2anHxoVt1ismnQ0P+UGWg7AXVqh2WILhBtlJVe8KHK/a+fZqaun19iOLI0yXDJq7AM83DyACvPiNDgO1aLChpn3U2euLMbMyPkeI2V3kBY8mkm60G3HWsuCvQEHmF4Mio1ILSAXkSpIPyuF2p5JB+r1ckIPdIkvLU5q6C6j2Z4btUhGX1oU8rvE/Wh5Vxok5EVeaNYTMNyr6ey69WGCzlQ5HL4rDCyKqoDPh2Rjh++tJZVxKF+0zKh2JE3Ch29MZwCBZSERBSH6BAT+7T5Nm4pCFbVR9lrbzYiUodo4YYTEtEKTPH2ca1exmR3DbUHgD4AAblo9OY/8yYnY+7VWZP1TcRLVZEtTq97B/S41oKCRbOfzvd7S4hpDjJTJBqWz7fNPpXLoWNSLrrczkUNuomIpgp8E+8YK7xPl45l4YBJmAvRDUx9/e0mPOPDaWzZpCCR+lKD0r2i/lIG52LWGP8WRcP3H1RmYCY44yUN4KUcR/8oLW11PaGUkKCD44AMbv6SDbx57s5r2xEFAvc9FW6ULrPSCE3qyjag4XGYOkTuiNnj6d9HTzyopWwExs2gFb2d/DTB0+M1rT/kZ442nCjueOUFskiPQthHv4iFb1WJIpYjY4EZWwpxapo4Y="
  api_key: # f71d
    secure: "QVIhFO8RFhMzP7YktL/M09QsGmj9HglCujrQUOEtvEbCcKbPsdFiNR6rUXiznYO07a8wFM443au1LaeWiEseQMhYmucZ5UBdtZQb7r1Ocxi09hWMP7X82PAJbU8sONF5HveHZN9oHNREHZS4PqNGXXPQTLkDvJ7qWM8/h9D3/TYW0LrujtEBDlL1YbWGsmYCTQNmHB8jlS7p4pSome6d3DEfX63HG1fq2u/NqOyHBdYx+tUSdK2t1t8MFFs28b5+gxAWtmRquCDobZ1Ybk3cG49z9qT4kmBQxoISo5QbjblJ5Ofh00YlLOv97XwAt5R0g5h23RzPgNqxw4KYviuIBtK7fMOdx06cZ+xlF7rsnEI5gagqloc4GCXJGnBJikR0eB4roAEhFElgDyek0zG4ZphUfmPd3iYKX6r96o+9Ypq76SMEqu77U7J6gQrBjoX9jgVAXGE0YEOJ5WdQQEqcFea8FKtKts8AzYIiIfc1dSlU307idYna1CrcRkg7WkiwxWb8wYQSZM79bKm7A2KnaV/bHCkXJdEHXs3NITVpYSbaKSNiLc9tkLXlLHYTMJj5xZIEZPjdX+Xe7hyleEDndDdvMjxBrFdBQU/I6ZOkncnjqEsaa/f5SdGsOlp5x5WgcV82gDxsaQxasgoYLBik0INHxZQrvkpsEmWIVgoot+A="
  on:
    tags: true
    node: lts/*
